FROM nginx:1.23.1-alpine

ADD ./nginx/default.conf /etc/nginx/conf.d/default.conf

ADD ./nginx/certs /etc/nginx/certs/self-signed

WORKDIR /usr/share/nginx/html

RUN chmod 777 -R /usr/share/nginx/html

EXPOSE 80

EXPOSE 443