version: '3'
services:
    nginx:
        build:
            context: ./
            dockerfile: Dockerfile.nginx
        # container_name: nginx
        networks:
            - digitaltechnologia
        ports:
            - 4000:80
        volumes:
            - ./wordpress/:/usr/share/nginx/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
    mysql:
        build:
            context: ./
            dockerfile: Dockerfile.sql
        restart: always
        container_name: ${MYSQL_DATABASE}
        networks:
            - digitaltechnologia
        volumes:
            - ./mysql/:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    php:
        build:
            context: ./
            dockerfile: Dockerfile.php
        # container_name: php
        networks:
            - digitaltechnologia
        volumes:
            - ./wordpress/:/usr/share/nginx/html
            - ./logs/xdebug.log:/var/log/xdebug.log
            - ./php/php.ini:/usr/local/etc/php/php.ini
networks:
    digitaltechnologia:
        driver: bridge
